sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - 'wget http://www.eu.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
  - 'tar xf zookeeper-3.4.6.tar.gz'
  - 'mv zookeeper-3.4.6/conf/zoo_sample.cfg zookeeper-3.4.6/conf/zoo.cfg'
  - './zookeeper-3.4.6/bin/zkServer.sh start'
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
